### PR TITLE
3.0.x compatibility

### PR DESCRIPTION
**Pull request by vilppuvuorinen**
* Added 3.0.x specific fixtures
* Updated deprecated finds with conditions to finds with where.

Did not actually test after extensive rebase. Let's see what will happen and patch things up later.

### CODE REVIEW

**Comment by vilppuvuorinen** [comment]
Seems like I didn't filter the feature specific updates from the fixtures. Filtering should fix the things.

**Comment by jfqd** [comment]
Couldn´t we check for jruby and use the old finder for it? Like

```
if defined? JRUBY_VERSION
  # use AR 3.x query
else
  # use AR 4.2 query
end
```

What do you think?

**Comment by vilppuvuorinen** [comment]
The whole ```find(:first, :conditions => [ ... ])``` query was deprecated after Rails 3 and even in Rails 3 it was only for legacy support. It would make no sense to go through hoops to get things working with jruby and AR 4.2 while the support is still in progress. Even simpler workaround would be possible, but I'd wait until the AR 4.2 support is finished before doing anything about it.

**Comment by jfqd** [comment]
Thanks for your work! Will merge it and add a hint in the readme about Redmine 3.0.x and jruby.

**Pull request merged**
