### PR TITLE
MacroExpander module

### PR DESCRIPTION
**Pull request by vilppuvuorinen**
I have added a module for the MacroExpander (#73 ). I ended up implementing the methods through a class inside the module to provide a pseudo-private scope for the functions. The major difference to #52 is that the macros are expanded also in first reply and Journal notes included in the message. 

TODO:
* Add tests
* Create update script

I'm getting this done a little slower than I thought. To be continued...

### CODE REVIEW

**Comment by vilppuvuorinen** [comment]
Seems like the slowest PR ever is drawing to an end. I ended up taking liberties like switching to purely migration based macro update.

@tatarevicova Supported characters in conversion of USER_CF_<name> are [A-Z0-9] is this sufficient or should underscores or other similar characters be added?

I'll squash the commits into a single commit if everything seems to be in place.

**Comment by tatarevicova** [comment]
For us it is sufficient, but I don't see the reason why the format should be limited (or at least limited more than it is in Redmine). I would allow any non-empty string after the USER_CF_. But I think it is not so important if it's only for the conversion script :-)

**Comment by jfqd** [comment]
@vilppuvuorinen Thank your for the good work. Please give me a note in this ticket when it is time to pull the request.

**Comment by vilppuvuorinen** [comment]
The commits are now squashed into a single one. Everything seems to be in order for a merge.

**Pull request merged**
