### PR TITLE
Unit and functional tests

### PR DESCRIPTION
**Pull request by vilppuvuorinen**
I have added some unit tests and functional tests to simplify development towards compatibility against new versions of Redmine. The tests currently pass against 2.4-stable, 2.5-stable and 2.6-stable.

The commits should probably be squashed into a single commit.

### CODE REVIEW

**Comment by vilppuvuorinen** [comment]
I'll squash those commits to clean up the commit history. Should I also look into the travis integration while I'm at it?

**Comment by jfqd** [comment]
@vilppuvuorinen Thanks for your work! I will test it hopefully on this weekend and pull it in.

If you have the time for the travis integration that would be really great!

**Comment by vilppuvuorinen** [comment]
I looked into the Travis integration and it seemed quite simple. I'll try to add it into this pull request during the weekend.

**Comment by vilppuvuorinen** [comment]
I added the Travis-CI integration and while I was at it I added also the CodeClimate Coverage integration. Resulting in the following row of badges:

[Build Status](https://travis-ci.org/jubicoy/redmine_helpdesk) [Code Climate](https://codeclimate.com/github/jubicoy/redmine_helpdesk) [Test Coverage](https://codeclimate.com/github/jubicoy/redmine_helpdesk)

Using the integrations should be pretty much plug and play with the exception of the coverage. Following part of the .travis.yml needs to be updated after merge:
```
addons:
  code_climate:
    repo_token:
      secure: Q7PftEoz...
```

**Comment by jfqd** [comment]
@vilppuvuorinen Thanks for the good work! Travis support is so helpful!

Last question: What is this Greeter class? Think we do not need it, right? If so, could you remove it before I pull it in?

**Comment by vilppuvuorinen** [comment]
The Greeter class is in no way related to the plugin. However, it is used as an attachment fixture used in the HelpdeskMailer's tests. Removing it would break the tests. I admit it is a poor choice for a file type, but I copied it from Redmine's fixtures.

**Comment by jfqd** [comment]
Thanks for your clarification! Merged it and will change the secure token for code climate in the next commit.

Do you have a twitter handle that I can mention you in a tweet?

**Comment by vilppuvuorinen** [comment]
You can use JubicOy. I don't have a personal handle but the company handle will do.

**Comment by jfqd** [comment]
@vilppuvuorinen Should we test against two databases? I think this is well testet with Rails and will speed up the tests if we only use MySQL or Postgres. What do you think?

**Comment by vilppuvuorinen** [comment]
I also find it hard to believe that ActiveSupport would have that sever bugs. Only legitimate issue that testing with both backends can reveal would be code that relies on a feature of a specific backend. I found one of these while writing those tests. The 40 run matrix is a bit overkill though.

If the build time is an issue 16 of the 40 runs could be excluded by removing the older versions of Redmine and run the tests only with 2.4.7, 2.5.3 and 2.6.2. The resulting 24 runs should add up to 1h 20min. Even further reduction could be achieved with only 2.5.3 and 2.6.2 against just a couple of Ruby versions with both backends. Such as 1.9.3, 2.0 and 2.1. This would add up to 3x2x2=12 runs that would add up to 40min.

The >2h run time is quite long, but the initial results are available under 3 minutes and a bad build can be stopped after that.

**Comment by jfqd** [comment]
@vilppuvuorinen Ok, I see the point related to the databases and will keep them both. But I would like to skip the tests for Redmine 2.5.2 and 2.6.0 and support only the latest releases to speed up the tests.

Will be fun to test Redmine 3.0 with Ruby 2.2 next :)

**Pull request merged**
