### PR TITLE
Cc handling

### PR DESCRIPTION
**Pull request by shackijj**
Business task was to notify recipients from "Cc" header about issue's flow.
So, I added handling of "Cc" header. If someone reports an issue by email and message has "Cc" header then addresses from "Cc" are saved in custom field "copy-to". Value of "copy-to" are added to email notifications about issue as "Cc" header.

### CODE REVIEW

**Comment by jfqd** [comment]
Well, what is this all about? Please provide a description.

**Comment by shackijj** [comment]
Sorry, it was my first fork on github.

Business task was to notify recipients from "Cc" header about issue's flow.
So, I added handling of "Cc" header. If someone reports an issue by email and email has "Cc" header then addresses from "Cc" are saved in custom field "copy-to". Value of "copy-to" are added to email notifications about issue as "Cc" header.

**Comment by jfqd** [comment]
@shackijj Thx for your work and sharing it! Could you add an option so that anybody can decide if they wanna use this feature or not? Personally I prefer to have the feature off by default.

Additionally a hint in the Readme would be fine so that people understand the usage of this feature.

**Comment by shackijj** [comment]
Done. The 'copy-to' checkbox in a project settings defines if 'cc handling' feature is enabled or not. Fields 'owner-email' and 'copy-to' are off by default.

We need to update README.md file and add info about this feature. Also, i noticed an undocumented 'send-to-supportcline-default' field. @jfqd Could you update README.md? I can try, but i'm not good in English.

**Comment by shackijj** [comment]
@jfqd The option was added and tested. README.md was updated.

**Comment by jfqd** [comment]
@shackijj Thx again. Sorry, had this week no time for the readme.

**Pull request merged**
