### PR TITLE
Add support for reply separator

### PR DESCRIPTION
**Pull request by tatarevicova**
- adds reply separator at the beginning of e-mails "sent to supportclient"
- cuts the reply separator and everything below it (removes the quoted text from the emails received from supportclients)

### CODE REVIEW

**Comment by vilppuvuorinen** [comment]
I have some concerns when it comes to hard gsubs before saving the journal. The list of what-ifs just goes on and on when it comes to reliability of this method. Separator compliance is also extremely critical.

The problem that is being solved here is cluttered history and by nature should be solved in Views. A JavaScript solution that collapses the quoted text (lines starting with '>') would be ideal. Even a solution that allows collapsing at a separator could be possible.

If everything else fails the gsubbing could also be moved to view making it possible to retrieve incorrectly formatted mail from db or after improving the separation method. Just anything but hard cut before storing could do it.

**Comment by tatarevicova** [comment]
> A JavaScript solution that collapses the quoted text (lines starting with '>') would be ideal.

A lot of email clients (including MS Outlook in default settings) are not adding the '>' to quoted lines.

> Just anything but hard cut before storing could do it.

This is the same thing redmine does with its body delimiters in mail handler. I don't see much difference in retrieving incorrectly formatted text from db or from the original email from the mailbox.

**Comment by vilppuvuorinen** [comment]
>>A JavaScript solution that collapses the quoted text (lines starting with '>') would be ideal.

>A lot of email clients (including MS Outlook in default settings) are not adding the '>' to quoted lines.

True. The inconsistent quote markup might be a problem.

>>Just anything but hard cut before storing could do it.

>This is the same thing redmine does with its body delimiters in mail handler.

 I'm aware that hard delimiting is also the approach in the core mailer features. That does not make it any better solutions.

>I don't see much difference in retrieving incorrectly formatted text from db or from the original email from the mailbox.

Doing the delimiting view first would allow show/hide toggle to be added later. I would assume that the delimiting works on most emails which would support delimiting by default. There could be a simple checkbox/button that would toggle a single class on the div containing the delimited text.

Retrieving missing info requires quite extensive privileges from either db or mailbox. The ideal solution would allow anyone with access to the Issue Journal to view the full message if necessary.

**Comment by jfqd** [comment]
Sorry for the long delay. Pulled this in. As mentioned by @vilppuvuorinen a JavaScript solution that collapses the quoted text would be fine.

**Pull request merged**
